version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build_test:
          context:
            - twine  # Provides TWINE_USERNAME and TWINE_PASSWORD
            - codecov  # Provides CODECOV_TOKEN

orbs:
  python: circleci/python@2.1.1
  codecov: codecov/codecov@5  # Updated to version 5

jobs:
  build_test:
    docker:
      - image: cimg/python:3.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Verify critical files
          command: |
            ls -l README.md setup.py bib_ami/bib_ami.py || exit 1
      - python/install-packages:
          pkg-manager: pip
          args: pytest pytest-cov twine sphinx sphinx_rtd_theme bibtexparser requests fuzzywuzzy python-Levenshtein
      - run:
          name: Verify Python version
          command: python3 --version
      - run:
          name: Run tests
          command: pytest --cov=./ --cov-report=xml
      - run:
          name: Build documentation
          command: |
            cd doc
            make html
            cd ..
      - run:
          name: Build distribution packages
          command: python3 setup.py sdist bdist_wheel
      - run:
          name: Upload to PyPI
          command: python3 -m twine upload dist/* --verbose
      - store_artifacts:
          path: doc/_build/html/
          destination: doc
      - store_artifacts:
          path: coverage.xml
      - codecov/upload:
          file: coverage.xml
          token: CODECOV_TOKEN